### ISSUE TITLE
Installing service

### ISSUE THREAD

**Issue by CarlosMartinPerez** [emerbrito/Windows-Service-Plus#4]
Hi,
I have downloaded your project base and started a project in visual studio. The program correctly works in debug mode. But when i want to install it with "InstallUtil.exe" (As i found in [Microsoft Documentation](https://msdn.microsoft.com/es-es/library/sd8zc8ha(v=vs.110).aspx)) it throws some error message:  
   

> No se pudieron encontrar instaladores públicos con el atributo RunInstallerAttribute.Yes en el ensamblado C:\Archivos de programa\DEBUG\Nadilux Periodical Tasks V0.8.5\Service\Nadilux Periodical Task Service.exe.
> Excepción durante la fase de retroceso al estado original del instalador System.Configuration.Install.AssemblyInstaller.
> System.IO.FileNotFoundException: No se pudo encontrar el archivo 'C:\Archivos de programa\DEBUG\Nadilux Periodical Tasks V0.8.5\Service\Nadilux Periodical Task Service.InstallState'.
> Excepción durante la fase de instalación de retroceso al estado original. Esta excepción se omitirá y se continuará con el retroceso al estado original. Sin embargo, puede que el equipo no recupere el estado inicial hasta que se haya completado esta fase.

It seems like a config param is wrong. If you have another method for make the installation i will be thankful if you can explain me how to do it. 
Regards, Carlos

**Comment by emerbrito** [comment]
Hi,

This project is basically setting up your environment to build a Topshelf service.
You can find detailed Topshelf documentation here [http://topshelf-project.com/](http://topshelf-project.com/). I recommend you taking a look at the overview page [https://topshelf.readthedocs.io/en/latest/overview/index.html](https://topshelf.readthedocs.io/en/latest/overview/index.html).

Since the service is an executable it can install itself, you don't need (and shouldn't use) "InstallUtil.exe".

At the very bottom of this page you can find examples of how to use command line to install the service [https://topshelf.readthedocs.io/en/latest/overview/commandline.html#examples](https://topshelf.readthedocs.io/en/latest/overview/commandline.html#examples).

I hope this helps.

**Comment by CarlosMartinPerez** [comment]
It is what iIwas looking for
